### ISSUE TITLE
Unable To Build for UWP.

### ISSUE THREAD

**Issue by AnandDixit27** [LightBuzz/Archiver-Unity#2]
I am using unity 2018.4.12 LTS version and MRTK-2.1.0 version in sample project and created a script which downloads a zip file and unzip it. It is working file in editor but when trying build for UWP Hololens build always failed here I am attaching project build configuration and error due to which build was failing.
![BuildConfig](https://user-images.githubusercontent.com/49301003/71822226-5cf79080-30ba-11ea-8f90-b4eaacd75b4c.png)
![LightBuzzArchieve](https://user-images.githubusercontent.com/49301003/71822254-700a6080-30ba-11ea-9e65-416f3899c0c2.png)

Please help me on this problem.

**Comment by AnandDixit27** [comment]
@Vangos 

Please reply to the same. I am waiting for your reply.

**Comment by Vangos** [comment]
Thank you for reporting the issue. Our team will check the issue and provide a solution when ready.

**Comment by yosun** [comment]
any update

**Comment by yosun** [comment]
https://forum.unity.com/threads/c-compression-zip-missing.577492/#post-3849472

**Comment by Vangos** [comment]
Check this https://github.com/LightBuzz/Archiver-Unity/issues/8#issuecomment-1073952037
