### ISSUE TITLE
InvalidDataException: Offset to Central Directory cannot be held in an Int64. 

### ISSUE THREAD

**Issue by pablopalma** [LightBuzz/Archiver-Unity#3]
Hey, i'm having this issue after downloading my zip file. 

The problem it's that the file corrupts after downloading. If i load locally works fine.

There's some solution to download the file without issues?

Thanks.

**Comment by Vangos** [comment]
Hi. Is the file an actual `.zip` file or a `.gz`/`.tar.gz` one?

**Comment by pablopalma** [comment]
Hi. I've solved it by changing the way of download my file.

Before did use the uwr.downloadHanlder.text that corrupts the zip file. Now i'm downloading with DownloadHandlerFile and works fine.

I'll mark the issue as solved.

**Comment by Vangos** [comment]
Great to hear. Thank you very much.
