### ISSUE TITLE
Extract and overwrite

### ISSUE THREAD

**Issue by bigelod** [LightBuzz/Archiver-Unity#5]
I needed the ability to extract a ZIP and overwrite any directory/folder as needed, and by default this causes errors if the file or folder exists already.

Reading online, looks like ZipArchive is needed to fix this, and by extension I added additional references to System.IO.Compression and System.IO.Compression.FileSystem as the default references does not have ZipArchive.

I then replaced:
`ZipFile.ExtractToDirectory(source, destination);`

With:
```
using (ZipArchive archive = ZipFile.OpenRead(source))
{
                foreach (ZipArchiveEntry entry in archive.Entries)
                {
                        string targetFile = Path.Combine(destination, entry.FullName);
                        Directory.CreateDirectory(Path.GetDirectoryName(targetFile));
                        entry.ExtractToFile(targetFile, true);
               }
 }
```

And now it's working the way I want in Unity Editor and Windows and Android/Oculus Quest builds. I do not have an iOS or Mac OSX device to test on.

Can this be added as a specific extraction mode to the main library? or is there a better way to do it than this?

**Comment by Vangos** [comment]
Thanks for reporting and fixing this. You can make a pull request and we shall then test the code on macOS and iOS.

**Comment by bigelod** [comment]
Great thanks Vangos! :)

**Comment by Vangos** [comment]
Thank you for the update! I have just merged your pull request to the `master` branch.

**Comment by bigelod** [comment]
Awesome thanks so much :)

**Comment by Vangos** [comment]
Also added you as a contributor (README.md).
